name: Convert GPX to GeoJSON

on:
  push:
    branches:
      - main  #

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
             npm install xmldom
             npm install @turf/turf
             npm install geojson-precision
             npm install fs

      - name: Convert GPX to GeoJSON
        run: node convert-gpx-to-geojson.js

      - name: Commit and Push GeoJSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.geojson
          git commit -m "Add converted GeoJSON files"
          git push
        

      - name: Generate index.html
        run: |
          node generate-map.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-generate Leaflet map with tracks"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
