name: Convert GPX to GeoJSON

on:
  push:
    branches:
      - main  #

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Convert GPX to GeoJSON
        run: node convert-gpx-to-geojson.js

      - name: Commit and Push GeoJSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.geojson
          git commit -m "Add converted GeoJSON files"
          git push

      - name: Trigger Workflow 2 (Generate Leaflet Map) via GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref":"refs/heads/main"}' \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/generate-leaflet-map.yml/dispatches"
